name: Android Debug Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Build süresi uzun olabilir

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk-version: 25.1.8937393
          cmake-version: 3.22.1

      - name: Download and extract MuPDF
        run: |
          mkdir -p app/src/main/cpp
          cd app/src/main/cpp
          wget https://mupdf.com/downloads/archive/mupdf-1.24.0-source.tar.gz
          tar -xzf mupdf-1.24.0-source.tar.gz
          mv mupdf-1.24.0-source mupdf_source
          rm mupdf-1.24.0-source.tar.gz
          echo "MuPDF downloaded successfully"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build with detailed logging
        run: ./gradlew :app:assembleDebug --info --stacktrace --no-daemon
      
      - name: Upload Debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: PDFly-Debug-APK
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Logs
          path: |
            **/*.log
            app/build/**/*.log
            app/.cxx/**/*.log
